`include ../../hw/asic/memories/sram8192x32m8.v
`include ../../hw/asic/memories/rf128x32m2.v
`include ../../hw/asic/fll/rtl/stubs/tsmc65_FLL_stub.v {do_not_override}
`include ../../hw/vendor/esl_epfl_coubertin/memory_macro/behavioural_model/bladeFF_3006.sv
`include ../../hw/asic/std_cells/sc8_cln65lp_base_hvt_neg.v {do_not_override}
`include ../../hw/asic/std_cells/sc8_cln65lp_base_lvt_neg.v {do_not_override}
`include ../../hw/asic/std_cells/sc8_cln65lp_base_rvt_neg.v {do_not_override}
`include ../../IP/Front_End/verilog/tcbn65lp_200a/tcbn65lp_pwr.v            
`include ../../IP/Front_End/verilog/tcbn65lpcglvt_200a/tcbn65lpcglvt_pwr.v      
`include ../../IP/Front_End/verilog/tcbn65lphpbwpcghvt_200a/tcbn65lphpbwpcghvt_pwr.v  
`include ../../IP/Front_End/verilog/tcbn65lphpbwplvt_140a/tcbn65lphpbwplvt_pwr.v  
`include ../../IP/Front_End/verilog/tcbn65lpcg_200a/tcbn65lpcg_pwr.v
`include ../../IP/Front_End/verilog/tcbn65lphpbwp_140a/tcbn65lphpbwp_pwr.v
`include ../../IP/Front_End/verilog/tcbn65lphpbwpcglvt_200a/tcbn65lphpbwpcglvt_pwr.v
`include ../../IP/Front_End/verilog/tcbn65lphvt_200a/tcbn65lphvt_pwr.v
`include ../../IP/Front_End/verilog/tpdn65lpnv2od3_140b/tpdn65lpnv2od3.v
`include ../../IP/Front_End/verilog/tpfn65lpgv2od3_140c/tpfn65lpgv2od3.v
`include ../../IP/Front_End/verilog/tcbn65lpcghvt_200a/tcbn65lpcghvt_pwr.v
`include ../../IP/Front_End/verilog/tcbn65lphpbwpcg_200a/tcbn65lphpbwpcg_pwr.v
`include ../../IP/Front_End/verilog/tcbn65lphpbwphvt_140a/tcbn65lphpbwphvt_pwr.v
`include ../../IP/Front_End/verilog/tcbn65lplvt_200a/tcbn65lplvt_pwr.v
`include ../../IP/Front_End/verilog/tphn65lpgv2od3_sl_140a/tphn65lpgv2od3_sl.v
`include ../../IP/Front_End/verilog/tpzn65lpgv2od3_200a/tpzn65lpgv2od3.v
