// This file is generated by gen_caesar_instruction.py on 2024-09-30
#ifndef CAESAR_INSTRUCTION_GEN_H
#define CAESAR_INSTRUCTION_GEN_H


constexpr char width_str[3][10] = {


     "WORD_32B",
     "WORD_16B",
     "WORD_8B"
};


enum elm_width_e {


     WORD_32B= 0,
     WORD_16B= 1,
     WORD_8B= 2
};


constexpr char op_str[18][16] = {


     "CSRW",
     "SHIFT_R",
     "SHIFT_L",
     "SUB",
     "ADD",
     "OR",
     "XOR",
     "AND",
     "MULT",
     "MAC_FIRST",
     "MAC",
     "STORE_MAC",
     "MIN",
     "MAX",
     "DOT_FIRST",
     "DOT",
     "STORE_DOT",
     "MAC_RELU"
};


#endif
